# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Etherscan < Formula
  desc "Command-line client and interactive explorer for the Etherscan V2 API"
  homepage "https://github.com/etherscan/etherscan-cli"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/etherscan/etherscan-cli/releases/download/v1.1.1/etherscan_1.1.1_darwin_amd64.tar.gz"
      sha256 "09ab40fa3af035a792d35a1d6e8be17d7238bdb17e1c8596930e34c1f60d040b"

      define_method(:install) do
        bin.install "etherscan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/etherscan/etherscan-cli/releases/download/v1.1.1/etherscan_1.1.1_darwin_arm64.tar.gz"
      sha256 "82abf8f84c0a6ce033d4dd8f462bb4bca6b443d05f67c87330eee0763e91b77e"

      define_method(:install) do
        bin.install "etherscan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/etherscan/etherscan-cli/releases/download/v1.1.1/etherscan_1.1.1_linux_amd64.tar.gz"
      sha256 "738625a2c00870f819b290e8e7dc63b432809717808226f84e060b70288333ac"
      define_method(:install) do
        bin.install "etherscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/etherscan/etherscan-cli/releases/download/v1.1.1/etherscan_1.1.1_linux_arm64.tar.gz"
      sha256 "8df93777e49093a2656f4f24882a87df50b955d61355a914ff504cb5b9bd017a"
      define_method(:install) do
        bin.install "etherscan"
      end
    end
  end

  test do
    system "#{bin}/etherscan", "version"
  end
end
