# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Etherscan < Formula
  desc "Command-line client and interactive explorer for the Etherscan V2 API"
  homepage "https://github.com/etherscan/etherscan-cli"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/etherscan/etherscan-cli/releases/download/v1.1.1/etherscan_1.1.1_darwin_amd64.tar.gz"
      sha256 "ab26af07a5496a0292127c24eb031d9f11b024d19c4f9d97b208b6a7a5aeea84"

      define_method(:install) do
        bin.install "etherscan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/etherscan/etherscan-cli/releases/download/v1.1.1/etherscan_1.1.1_darwin_arm64.tar.gz"
      sha256 "0349009a3c227e14dedd0a7c20ae26ca2bafe3b791df0c2792e1164b3e59ecdf"

      define_method(:install) do
        bin.install "etherscan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/etherscan/etherscan-cli/releases/download/v1.1.1/etherscan_1.1.1_linux_amd64.tar.gz"
      sha256 "f3b750fe1cc583169d351208851d47c23a8aac5bd41b873252df4a6f46033e6e"
      define_method(:install) do
        bin.install "etherscan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/etherscan/etherscan-cli/releases/download/v1.1.1/etherscan_1.1.1_linux_arm64.tar.gz"
      sha256 "a308529abc05b8999a3079239b51d931a904fceabc0594a4a94c170d1217a666"
      define_method(:install) do
        bin.install "etherscan"
      end
    end
  end

  test do
    system "#{bin}/etherscan", "version"
  end
end
